import { FormEvent,useState } from 'react'
import { useQuery,useQueryClient } from '@tanstack/react-query'
import { api } from '../../services/api'
import { useAuth } from '../../app/AuthProvider'
import { canPermission,isAdmin } from '../../lib/permissions'
import { Button,Card,Empty,ErrorBox,Field,Input,Modal,Select,Spinner,Textarea,Badge } from '../../components/ui'
import { eventTypeLabel,formatDateTime } from '../../lib/format'
import { getErrorMessage } from '../../lib/errors'
import { fromDateTimeLocal, toDateTimeLocal } from '../../lib/dateTime'

export function EventsPage(){
 const {context}=useAuth();const qc=useQueryClient();const [orgId,setOrgId]=useState('all');const [editing,setEditing]=useState<any>(null);const [participantsEvent,setParticipantsEvent]=useState<any>(null);const [error,setError]=useState('');const [message,setMessage]=useState('')
 const {data=[],isLoading}=useQuery({queryKey:['events',orgId],queryFn:()=>api.events.list(orgId==='all'?undefined:orgId),enabled:!!context})
 const manageable=(context?.organizations??[]).filter(o=>isAdmin(context)||canPermission(context,'event.manage',o.id))
 const save=async(v:any)=>{try{if(v.id)await api.events.update(v.id,v);else await api.events.create(v);await qc.invalidateQueries({queryKey:['events']});setEditing(null)}catch(e){setError(getErrorMessage(e))}}
 const register=async(id:string)=>{try{await api.events.register(id);setMessage('참가 신청이 완료되었습니다.');await qc.invalidateQueries({queryKey:['events']})}catch(e){setError(getErrorMessage(e))}}
 const cancel=async(id:string)=>{try{await api.events.cancel(id);setMessage('참가 신청을 취소했습니다.');await qc.invalidateQueries({queryKey:['events']})}catch(e){setError(getErrorMessage(e))}}
 const del=async(id:string)=>{if(!confirm('일정을 삭제할까요?'))return;try{await api.events.delete(id);await qc.invalidateQueries({queryKey:['events']})}catch(e){setError(getErrorMessage(e))}}
 return <div className="stack-lg"><div className="page-header"><div><h1>일정</h1><p>예정된 행사와 조직별 일정을 관리합니다.</p></div>{manageable.length>0&&<Button onClick={()=>setEditing({organization_id:manageable[0].id,type:'other',title:'',description:'',starts_at:'',ends_at:'',location:'',capacity:null,status:'draft'})}>일정 만들기</Button>}</div>
 {error&&<ErrorBox message={error}/>} {message&&<div className="success-box">{message}</div>}
 <Card><Field label="조직 필터"><Select value={orgId} onChange={e=>setOrgId(e.target.value)}><option value="all">전체</option>{context?.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field></Card>
 {isLoading?<Spinner/>:data.length?<div className="grid-2">{data.map(e=>{const manageableEvent=isAdmin(context)||(e.organization_id?canPermission(context,'event.manage',e.organization_id):false);return <Card key={e.id}><div className="badges"><Badge>{eventTypeLabel(e.type)}</Badge><Badge tone={e.status==='published'?'success':e.status==='cancelled'?'danger':'neutral'}>{e.status}</Badge></div><h2>{e.title}</h2><p>{e.description||'설명 없음'}</p><div className="meta"><span>🗓 {formatDateTime(e.starts_at)}</span><span>📍 {e.location||'장소 미정'}</span>{e.capacity&&<span>👥 {e.capacity}명</span>}</div><div className="actions">{e.status==='published'&&<><Button onClick={()=>register(e.id)}>참가 신청</Button><Button variant="secondary" onClick={()=>cancel(e.id)}>참가 취소</Button></>}{manageableEvent&&<><Button variant="secondary" onClick={()=>setParticipantsEvent(e)}>참가자</Button><Button variant="secondary" onClick={()=>setEditing(e)}>수정</Button><Button variant="danger" onClick={()=>del(e.id)}>삭제</Button></>}</div></Card>})}</div>:<Card><Empty>일정이 없습니다.</Empty></Card>}
 {participantsEvent&&<ParticipantsModal event={participantsEvent} onClose={()=>setParticipantsEvent(null)}/>} {editing&&<EventModal value={editing} organizations={manageable} onClose={()=>setEditing(null)} onSave={save}/>}</div>
}
function EventModal({value,organizations,onClose,onSave}:{value:any;organizations:any[];onClose:()=>void;onSave:(v:any)=>Promise<void>}){const [v,setV]=useState(value);const submit=(e:FormEvent)=>{e.preventDefault();void onSave(v)};return <Modal title={v.id?'일정 수정':'일정 만들기'} onClose={onClose}><form onSubmit={submit} className="stack"><Field label="조직"><Select value={v.organization_id||''} onChange={e=>setV({...v,organization_id:e.target.value})} required>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field><div className="form-grid"><Field label="유형"><Select value={v.type} onChange={e=>setV({...v,type:e.target.value})}>{['worship','church_event','retreat','small_group','club','volunteer','other'].map(x=><option key={x} value={x}>{eventTypeLabel(x)}</option>)}</Select></Field><Field label="상태"><Select value={v.status} onChange={e=>setV({...v,status:e.target.value})}>{['draft','published','cancelled','completed'].map(x=><option key={x}>{x}</option>)}</Select></Field></div><Field label="제목"><Input value={v.title} onChange={e=>setV({...v,title:e.target.value})} maxLength={200} required/></Field><Field label="설명"><Textarea rows={4} value={v.description||''} onChange={e=>setV({...v,description:e.target.value})}/></Field><div className="form-grid"><Field label="시작"><Input type="datetime-local" value={toDateTimeLocal(v.starts_at)} onChange={e=>setV({...v,starts_at:fromDateTimeLocal(e.target.value)})} required/></Field><Field label="종료"><Input type="datetime-local" value={toDateTimeLocal(v.ends_at)} onChange={e=>setV({...v,ends_at:fromDateTimeLocal(e.target.value)})}/></Field></div><div className="form-grid"><Field label="장소"><Input value={v.location||''} onChange={e=>setV({...v,location:e.target.value})}/></Field><Field label="정원"><Input type="number" min={1} value={v.capacity??''} onChange={e=>setV({...v,capacity:e.target.value?Number(e.target.value):null})}/></Field></div><div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>취소</Button><Button>저장</Button></div></form></Modal>}

function ParticipantsModal({event,onClose}:{event:any;onClose:()=>void}){const {data=[],isLoading}=useQuery({queryKey:['event-participants',event.id],queryFn:()=>api.events.participants(event.id)});return <Modal title={`${event.title} · 참가자`} onClose={onClose}>{isLoading?<Spinner/>:data.length?<div className="list">{data.map((p:any)=><div className="list-row" key={p.user_id}><div><strong>{p.user_id}</strong><small>{formatDateTime(p.registered_at)}</small></div><Badge tone={p.cancelled_at?'danger':'success'}>{p.cancelled_at?'취소':'참가'}</Badge></div>)}</div>:<Empty>참가자가 없습니다.</Empty>}</Modal>}
