import { FormEvent,useState } from 'react'
import { useQuery,useQueryClient } from '@tanstack/react-query'
import { api } from '../../services/api'
import { useAuth } from '../../app/AuthProvider'
import { canPermission,isAdmin } from '../../lib/permissions'
import { Button,Card,Empty,ErrorBox,Field,Input,Modal,Select,Spinner,Textarea,Badge } from '../../components/ui'
import { formatDateTime } from '../../lib/format'
import { getErrorMessage } from '../../lib/errors'

export function PrayerPage(){
 const {context}=useAuth();const [orgId,setOrgId]=useState(context?.memberships.find(m=>m.status==='active')?.organization_id||'');const [create,setCreate]=useState(false);const [error,setError]=useState('');const qc=useQueryClient()
 const {data=[],isLoading}=useQuery({queryKey:['prayers',orgId],queryFn:()=>api.prayers.list(orgId),enabled:!!orgId})
 if(!orgId)return <Card><Empty>기도제목을 볼 조직이 없습니다.</Empty></Card>
 return <div className="stack-lg"><div className="page-header"><div><h1>기도제목</h1><p>함께 기도하고 서로를 격려하세요.</p></div><Button onClick={()=>setCreate(true)}>기도제목 작성</Button></div>{error&&<ErrorBox message={error}/>}<Card><Field label="조직"><Select value={orgId} onChange={e=>setOrgId(e.target.value)}>{context?.organizations.filter(o=>context.memberships.some(m=>m.organization_id===o.id&&m.status==='active')).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field></Card>
 {isLoading?<Spinner/>:data.length?<div className="grid-2">{data.map(p=><PrayerCard key={p.id} prayer={p} userId={context.profile!.id} onError={setError}/>)}</div>:<Card><Empty>게시된 기도제목이 없습니다.</Empty></Card>}
 {create&&<PrayerModal organizationId={orgId} userId={context.profile!.id} onClose={()=>setCreate(false)} onDone={async()=>{setCreate(false);await qc.invalidateQueries({queryKey:['prayers',orgId]})}} onError={setError}/>}</div>
}
function PrayerCard({prayer,userId,onError}:{prayer:any;userId:string;onError:(s:string)=>void}){const [reacted,setReacted]=useState(prayer.reacted_by_me);const [count,setCount]=useState(prayer.reaction_count);const [busy,setBusy]=useState(false);const toggle=async()=>{setBusy(true);try{await api.prayers.react(prayer.id,userId,reacted);setReacted(!reacted);setCount(count+(reacted?-1:1))}catch(e){onError(getErrorMessage(e))}finally{setBusy(false)}};return <Card><div className="article-head"><div><Badge>{prayer.visibility==='public'?'공개':'나만 보기'}</Badge><h2>{prayer.title||'기도제목'}</h2><small>{prayer.is_anonymous?'익명':prayer.visible_author_name||'회원'} · {formatDateTime(prayer.created_at)}</small></div></div><p className="article-body">{prayer.body}</p>{prayer.visibility==='public'&&<Button variant={reacted?'primary':'secondary'} disabled={busy} onClick={()=>void toggle()}>🙏 {count}</Button>}</Card>}
function PrayerModal({organizationId,userId,onClose,onDone,onError}:{organizationId:string;userId:string;onClose:()=>void;onDone:()=>Promise<void>;onError:(s:string)=>void}){const [v,setV]=useState<{title:string;body:string;visibility:'public'|'private';is_anonymous:boolean}>({title:'',body:'',visibility:'public',is_anonymous:false});return <Modal title="기도제목 작성" onClose={onClose}><form className="stack" onSubmit={async e=>{e.preventDefault();try{await api.prayers.create({...v,organization_id:organizationId,author_id:userId,status:'published'});await onDone()}catch(err){onError(getErrorMessage(err))}}}><Field label="제목"><Input value={v.title} onChange={e=>setV({...v,title:e.target.value})}/></Field><Field label="내용"><Textarea rows={8} value={v.body} onChange={e=>setV({...v,body:e.target.value})} required maxLength={5000}/></Field><div className="form-grid"><Field label="공개 범위"><Select value={v.visibility} onChange={e=>setV({...v,visibility:e.target.value})}><option value="public">조직 공개</option><option value="private">나만 보기</option></Select></Field><Field label="익명"><Select value={String(v.is_anonymous)} onChange={e=>setV({...v,is_anonymous:e.target.value==='true'})}><option value="false">아니오</option><option value="true">예</option></Select></Field></div><div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>취소</Button><Button>게시</Button></div></form></Modal>}
export function MediaPage(){
 const {context}=useAuth();const [orgId,setOrgId]=useState('all');const [editing,setEditing]=useState<any>(null);const [error,setError]=useState('');const qc=useQueryClient();const {data=[],isLoading}=useQuery({queryKey:['media',orgId],queryFn:()=>api.media.list(orgId==='all'?undefined:orgId),enabled:!!context});const manageable=(context?.organizations??[]).filter(o=>isAdmin(context)||canPermission(context,'media.manage',o.id))
 const save=async(v:any)=>{try{if(v.id)await api.media.update(v.id,v);else await api.media.create(v);await qc.invalidateQueries({queryKey:['media']});setEditing(null)}catch(e){setError(getErrorMessage(e))}}
 return <div className="stack-lg"><div className="page-header"><div><h1>미디어</h1><p>사진, 영상, 오디오, 문서를 관리합니다.</p></div>{manageable.length>0&&<Button onClick={()=>setEditing({organization_id:manageable[0].id,type:'document',title:'',description:'',external_url:'',status:'published'})}>미디어 추가</Button>}</div>{error&&<ErrorBox message={error}/>}<Card><Field label="조직"><Select value={orgId} onChange={e=>setOrgId(e.target.value)}><option value="all">전체</option>{context?.organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field></Card>{isLoading?<Spinner/>:data.length?<div className="grid-3">{data.map(m=><Card key={m.id}><Badge>{m.type}</Badge><h2>{m.title}</h2><p>{m.description||''}</p>{m.external_url&&<a href={m.external_url} target="_blank" rel="noreferrer" className="text-link">열기 ↗</a>}{m.storage_path&&<p className="muted">스토리지: {m.storage_path}</p>}{(isAdmin(context)||(m.organization_id&&canPermission(context,'media.manage',m.organization_id)))&&<div className="actions"><Button variant="secondary" onClick={()=>setEditing(m)}>수정</Button><Button variant="danger" onClick={async()=>{if(confirm('삭제할까요?')){try{await api.media.delete(m.id);await qc.invalidateQueries({queryKey:['media']})}catch(e){setError(getErrorMessage(e))}}}}>삭제</Button></div>}</Card>)}</div>:<Card><Empty>미디어가 없습니다.</Empty></Card>}{editing&&<MediaModal value={editing} organizations={manageable} onClose={()=>setEditing(null)} onSave={save}/>}</div>
}
function MediaModal({value,organizations,onClose,onSave}:{value:any;organizations:any[];onClose:()=>void;onSave:(v:any)=>Promise<void>}){const [v,setV]=useState(value);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');let uploadedPath:string|null=null;try{let next={...v};if(file){if(file.size>50*1024*1024) throw new Error('미디어 파일은 최대 50MB까지 업로드할 수 있습니다.');const uploaded=await api.storage.uploadMedia(v.organization_id,file);uploadedPath=uploaded.path;next={...next,...uploaded,storage_path:uploaded.path,storage_bucket:uploaded.bucket,external_url:null,status:v.status||'published'}}await onSave(next)}catch(err){if(uploadedPath) await api.storage.delete('sdm-media',uploadedPath).catch(()=>undefined);setError(getErrorMessage(err))}finally{setBusy(false)}};return <Modal title={v.id?'미디어 수정':'미디어 추가'} onClose={onClose}><form className="stack" onSubmit={submit}>{error&&<ErrorBox message={error}/>}<Field label="조직"><Select value={v.organization_id||''} onChange={e=>setV({...v,organization_id:e.target.value})} required>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field><Field label="유형"><Select value={v.type} onChange={e=>setV({...v,type:e.target.value})}>{['video','photo','audio','document'].map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="제목"><Input value={v.title} onChange={e=>setV({...v,title:e.target.value})} required maxLength={200}/></Field><Field label="설명"><Textarea value={v.description||''} onChange={e=>setV({...v,description:e.target.value})}/></Field><Field label="외부 URL"><Input type="url" value={v.external_url||''} onChange={e=>setV({...v,external_url:e.target.value,storage_path:null,storage_bucket:null})} placeholder="https://..."/></Field><Field label="파일 업로드"><Input type="file" onChange={e=>{setFile(e.target.files?.[0]||null);setV({...v,external_url:null})}}/></Field><Field label="상태"><Select value={v.status} onChange={e=>setV({...v,status:e.target.value})}><option value="published">게시</option><option value="draft">임시저장</option><option value="archived">보관</option></Select></Field><div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>취소</Button><Button disabled={busy}>저장</Button></div></form></Modal>}
