import { FormEvent,useState } from 'react'
import { useQuery,useQueryClient } from '@tanstack/react-query'
import { useAuth } from '../../app/AuthProvider'
import { api } from '../../services/api'
import { Button,Card,Empty,ErrorBox,Field,Input,Spinner,Badge,Select } from '../../components/ui'
import { formatDateTime } from '../../lib/format'
import { getErrorMessage } from '../../lib/errors'

export function ProfilePage(){
 const {context,refresh}=useAuth();const [v,setV]=useState({display_name:context?.profile?.display_name||'',birth_date:context?.profile?.birth_date||'',phone:context?.profile?.phone||'',profile_image_path:context?.profile?.profile_image_path||''});const [error,setError]=useState('');const [message,setMessage]=useState('')
 if(!context?.profile)return <Spinner/>
 const submit=async(e:FormEvent)=>{e.preventDefault();try{await api.profiles.updateSelf(v);await refresh();setMessage('프로필이 저장되었습니다.')}catch(err){setError(getErrorMessage(err))}}
 return <div className="stack-lg"><div className="page-header"><div><h1>내 프로필</h1><p>개인 정보를 확인하고 수정합니다.</p></div></div><Card><form className="stack" onSubmit={submit}>{error&&<ErrorBox message={error}/>} {message&&<div className="success-box">{message}</div>}<Field label="이름"><Input value={v.display_name} maxLength={100} onChange={e=>setV({...v,display_name:e.target.value})} required/></Field><Field label="이메일"><Input value={context.profile.email||''} disabled/></Field><div className="form-grid"><Field label="생년월일"><Input type="date" value={v.birth_date} onChange={e=>setV({...v,birth_date:e.target.value})}/></Field><Field label="전화번호"><Input value={v.phone} maxLength={30} onChange={e=>setV({...v,phone:e.target.value})}/></Field></div><Field label="프로필 이미지 경로"><Input value={v.profile_image_path} onChange={e=>setV({...v,profile_image_path:e.target.value})} placeholder={`profiles/${context.profile.id}/...`}/></Field><Field label="프로필 이미지 업로드" hint="JPG, PNG, WebP · 최대 5MB"><Input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){setError('프로필 이미지는 최대 5MB까지 업로드할 수 있습니다.');e.currentTarget.value='';return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('JPG, PNG, WebP 이미지만 업로드할 수 있습니다.');e.currentTarget.value='';return}try{setError('');const path=await api.storage.uploadProfileImage(context.profile!.id,file);setV(prev=>({...prev,profile_image_path:path}));setMessage('이미지가 업로드되었습니다. 저장 버튼으로 프로필을 반영하세요.')}catch(err){setError(getErrorMessage(err))}}}/></Field><Button>저장</Button></form></Card><Card><h2>내 역할</h2><div className="badges">{context.assignments.map(a=><Badge key={a.id}>{context.roles.find(r=>r.id===a.role_id)?.name||a.role_id}</Badge>)}</div></Card></div>
}

export function NotificationsPage(){
 const {context}=useAuth();const qc=useQueryClient();const [error,setError]=useState('');const {data=[],isLoading}=useQuery({queryKey:['notifications'],queryFn:api.notifications.list,enabled:!!context});const {data:prefs}=useQuery({queryKey:['notification-prefs',context?.profile?.id],queryFn:()=>api.notifications.preferences(context!.profile!.id),enabled:!!context?.profile})
 const savePrefs=async(enabled:boolean)=>{try{await api.notifications.savePreferences(context!.profile!.id,enabled);await qc.invalidateQueries({queryKey:['notification-prefs']})}catch(e){setError(getErrorMessage(e))}}
 const mark=async(id:string)=>{try{await api.notifications.markRead(id);await qc.invalidateQueries({queryKey:['notifications']})}catch(e){setError(getErrorMessage(e))}}
 return <div className="stack-lg"><div className="page-header"><div><h1>알림</h1><p>내 알림과 수신 설정을 관리합니다.</p></div></div>{error&&<ErrorBox message={error}/>}<Card><div className="section-title"><div><h2>알림 수신</h2><p>향후 푸시 알림 연동을 위한 기본 설정입니다.</p></div><Select value={String(prefs?.enabled??true)} onChange={e=>void savePrefs(e.target.value==='true')}><option value="true">사용</option><option value="false">사용 안 함</option></Select></div></Card>{isLoading?<Spinner/>:data.length?<div className="list">{data.map(n=><Card key={n.id} className={n.read_at?'':'unread'}><div className="article-head"><div><h2>{n.title}</h2><p>{n.body}</p><small>{formatDateTime(n.created_at)}</small></div>{!n.read_at&&<Button onClick={()=>void mark(n.id)}>읽음</Button>}</div></Card>)}</div>:<Card><Empty>알림이 없습니다.</Empty></Card>}</div>
}
