import { useState } from 'react'
import { useQuery,useQueryClient } from '@tanstack/react-query'
import { api } from '../../services/api'
import { useAuth } from '../../app/AuthProvider'
import { Button,Card,Empty,ErrorBox,Field,Input,Modal,Select,Spinner,Badge } from '../../components/ui'
import { formatDateTime } from '../../lib/format'
import { getErrorMessage } from '../../lib/errors'

export function AdminPage(){
 const {context}=useAuth();const qc=useQueryClient();const [tab,setTab]=useState<'roles'|'audit'|'notifications'>('roles');const [assign,setAssign]=useState(false);const [error,setError]=useState('')
 const {data:assignments=[],isLoading}=useQuery({queryKey:['all-role-assignments'],queryFn:api.roles.assignments,enabled:!!context});const {data:audit=[]}=useQuery({queryKey:['audit'],queryFn:api.audit.list,enabled:!!context});const {data:notificationSettings=[],isLoading:settingsLoading}=useQuery({queryKey:['notification-settings'],queryFn:api.notificationSettings.list,enabled:!!context&&tab==='notifications'})
 if(!context)return <Spinner/>
 return <div className="stack-lg"><div className="page-header"><div><span className="eyebrow">ADMIN</span><h1>관리자</h1><p>전체 역할 할당과 감사 로그를 관리합니다.</p></div><Button onClick={()=>setAssign(true)}>역할 할당</Button></div>{error&&<ErrorBox message={error}/>}<div className="tabs"><Button variant={tab==='roles'?'primary':'secondary'} onClick={()=>setTab('roles')}>역할 할당</Button><Button variant={tab==='audit'?'primary':'secondary'} onClick={()=>setTab('audit')}>감사 로그</Button><Button variant={tab==='notifications'?'primary':'secondary'} onClick={()=>setTab('notifications')}>알림 정책</Button></div>{tab==='roles'?(isLoading?<Spinner/>:<Card><div className="table-wrap"><table><thead><tr><th>사용자</th><th>역할</th><th>조직</th><th>생성일</th><th></th></tr></thead><tbody>{assignments.map(a=><tr key={a.id}><td>{a.user_id}</td><td>{context.roles.find(r=>r.id===a.role_id)?.name||a.role_id}</td><td>{a.organization_id?context.organizations.find(o=>o.id===a.organization_id)?.name||a.organization_id:'전체'}</td><td>{formatDateTime(a.created_at)}</td><td><Button variant="danger" onClick={async()=>{if(!confirm('역할을 삭제할까요?'))return;try{await api.roles.remove(a.id);await qc.invalidateQueries({queryKey:['all-role-assignments']});await qc.invalidateQueries({queryKey:['context']})}catch(e){setError(getErrorMessage(e))}}}>삭제</Button></td></tr>)}</tbody></table></div></Card>):tab==='audit'?<Card><div className="table-wrap"><table><thead><tr><th>시간</th><th>행위</th><th>대상</th><th>조직</th></tr></thead><tbody>{audit.map((a:any)=><tr key={a.id}><td>{formatDateTime(a.created_at)}</td><td>{a.action}</td><td>{a.entity_type}</td><td>{a.organization_id||'-'}</td></tr>)}</tbody></table></div></Card>:settingsLoading?<Spinner/>:<Card><div className="list">{notificationSettings.map((n:any)=><div className="list-row" key={n.key}><div><strong>{n.key}</strong><small>마지막 변경: {formatDateTime(n.updated_at)}</small></div><Select value={String(n.enabled)} onChange={async e=>{try{await api.notificationSettings.save(n.key,e.target.value==='true');await qc.invalidateQueries({queryKey:['notification-settings']})}catch(err){setError(getErrorMessage(err))}}}><option value="true">사용</option><option value="false">사용 안 함</option></Select></div>)}</div></Card>}
 {assign&&<RoleModal roles={context.roles} organizations={context.organizations} onClose={()=>setAssign(false)} onSave={async(v)=>{try{await api.roles.assign(v);setAssign(false);await qc.invalidateQueries({queryKey:['all-role-assignments']})}catch(e){setError(getErrorMessage(e))}}}/>}</div>
}
function RoleModal({roles,organizations,onClose,onSave}:{roles:any[];organizations:any[];onClose:()=>void;onSave:(v:any)=>Promise<void>}){const [v,setV]=useState({user_id:'',role_id:roles.find(r=>r.key==='team_leader')?.id||roles[0]?.id||'',organization_id:null as string|null});const role=roles.find(r=>r.id===v.role_id);const compatibleOrganizations=organizations.filter(o=>{if(role?.scope_type!=='organization') return false; return ({team:'team',small_group:'small_group',club:'club',volunteer_team:'volunteer_team'} as Record<string,string>)[role.key]===o.type || role.key==='pastor'});return <Modal title="역할 할당" onClose={onClose}><form className="stack" onSubmit={e=>{e.preventDefault();void onSave(v)}}><Field label="사용자 ID"><Input value={v.user_id} onChange={e=>setV({...v,user_id:e.target.value})} placeholder="UUID" required/></Field><Field label="역할"><Select value={v.role_id} onChange={e=>setV({...v,role_id:e.target.value,organization_id:null})}>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</Select></Field>{role?.scope_type==='organization'&&<Field label="조직"><Select value={v.organization_id||''} onChange={e=>setV({...v,organization_id:e.target.value})} required><option value="">선택</option>{compatibleOrganizations.filter(o=>o.status==='active').map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select></Field>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>취소</Button><Button>할당</Button></div></form></Modal>}
