import { FormEvent,useState } from 'react'
import { useQuery,useQueryClient } from '@tanstack/react-query'
import { api } from '../../services/api'
import { useAuth } from '../../app/AuthProvider'
import { isAdmin } from '../../lib/permissions'
import { Button,Card,Empty,Spinner,Badge,Field,Input,Modal,Select,Textarea,ErrorBox } from '../../components/ui'
import { getErrorMessage } from '../../lib/errors'
import { formatDateTime } from '../../lib/format'
import { fromDateTimeLocal, toDateTimeLocal } from '../../lib/dateTime'

export function WorshipPage(){
 const {context}=useAuth();const qc=useQueryClient();const [editing,setEditing]=useState<any>(null);const [error,setError]=useState('');const {data=[],isLoading}=useQuery({queryKey:['worship'],queryFn:()=>api.worship.list(),enabled:!!context})
 return <div className="stack-lg"><div className="page-header"><div><h1>예배</h1><p>예배 일정과 설교 정보를 확인합니다.</p></div>{isAdmin(context)&&<Button onClick={()=>setEditing({title:'',starts_at:'',ends_at:'',location:'',preacher_name:'',sermon_title:'',bible_reference:'',praise_info:'',description:'',is_published:false,organization_id:null})}>예배 등록</Button>}</div>{error&&<ErrorBox message={error}/>}{isLoading?<Spinner/>:data.length?<div className="grid-2">{data.map(w=><Card key={w.id}><div className="badges"><Badge tone={w.is_published?'success':'neutral'}>{w.is_published?'게시':'비공개'}</Badge></div><h2>{w.title}</h2><div className="meta"><span>🗓 {formatDateTime(w.starts_at)}</span><span>📍 {w.location||'장소 미정'}</span>{w.preacher_name&&<span>🎤 {w.preacher_name}</span>}{w.sermon_title&&<span>📖 {w.sermon_title}</span>}{w.bible_reference&&<span>{w.bible_reference}</span>}</div>{w.description&&<p className="article-body">{w.description}</p>}{isAdmin(context)&&<div className="actions"><Button variant="secondary" onClick={()=>setEditing(w)}>수정</Button><Button variant="danger" onClick={async()=>{if(!confirm('삭제할까요?'))return;try{await api.worship.delete(w.id);await qc.invalidateQueries({queryKey:['worship']})}catch(e){setError(getErrorMessage(e))}}}>삭제</Button></div>}</Card>)}</div>:<Card><Empty>등록된 예배가 없습니다.</Empty></Card>}{editing&&<WorshipModal value={editing} onClose={()=>setEditing(null)} onSave={async(v)=>{try{if(v.id)await api.worship.update(v.id,v);else await api.worship.create(v);await qc.invalidateQueries({queryKey:['worship']});setEditing(null)}catch(e){setError(getErrorMessage(e))}}}/>}</div>
}

function WorshipModal({value,onClose,onSave}:{value:any;onClose:()=>void;onSave:(v:any)=>Promise<void>}){const [v,setV]=useState(value);return <Modal title={v.id?'예배 수정':'예배 등록'} onClose={onClose}><form className="stack" onSubmit={(e:FormEvent)=>{e.preventDefault();void onSave(v)}}><Field label="제목"><Input value={v.title} onChange={e=>setV({...v,title:e.target.value})} required maxLength={200}/></Field><div className="form-grid"><Field label="시작"><Input type="datetime-local" value={toDateTimeLocal(v.starts_at)} onChange={e=>setV({...v,starts_at:fromDateTimeLocal(e.target.value)})} required/></Field><Field label="종료"><Input type="datetime-local" value={toDateTimeLocal(v.ends_at)} onChange={e=>setV({...v,ends_at:fromDateTimeLocal(e.target.value)})}/></Field></div><div className="form-grid"><Field label="장소"><Input value={v.location||''} onChange={e=>setV({...v,location:e.target.value})}/></Field><Field label="설교자"><Input value={v.preacher_name||''} onChange={e=>setV({...v,preacher_name:e.target.value})}/></Field></div><div className="form-grid"><Field label="설교 제목"><Input value={v.sermon_title||''} onChange={e=>setV({...v,sermon_title:e.target.value})}/></Field><Field label="본문"><Input value={v.bible_reference||''} onChange={e=>setV({...v,bible_reference:e.target.value})}/></Field></div><Field label="찬양 정보"><Input value={v.praise_info||''} onChange={e=>setV({...v,praise_info:e.target.value})}/></Field><Field label="설명"><Textarea value={v.description||''} onChange={e=>setV({...v,description:e.target.value})}/></Field><Field label="게시"><Select value={String(v.is_published)} onChange={e=>setV({...v,is_published:e.target.value==='true'})}><option value="false">비공개</option><option value="true">게시</option></Select></Field><div className="modal-actions"><Button type="button" variant="secondary" onClick={onClose}>취소</Button><Button>저장</Button></div></form></Modal>}
